apiVersion: v2
name: tolgee
description: This is the unofficial helm package for Tolgee.io project.
type: application
version: 0.4.0
appVersion: "3.120.0"
icon: https://tolgee.io/img/tolgeeLogo.svg
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.6.5
    alias: postgresql
    condition: postgresql.enabled
