apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tolgee.fullname" . }}
  labels:
    {{- include "tolgee.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "tolgee.fullname" . }}
  selector:
    matchLabels:
      {{- include "tolgee.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tolgee.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tolgee.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /
              port: http
          {{- if .Values.tolgee.envFromSecretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.tolgee.envFromSecretName }}
          {{- end }}
          env:
            - name: "tolgee.postgres-autostart.enabled"
              value: 'false'
            - name: "spring.datasource.url"
              value: 'jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.postgresqlDatabase }}'
            - name: "spring.datasource.username"
              value: {{ .Values.postgresql.auth.username }}
            - name: "spring.datasource.password"
              value: {{ .Values.postgresql.auth.password }}
            {{- range $key, $value := .Values.tolgee.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: {{ include "tolgee.fullname" . }}-pvc
              mountPath: /data/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "tolgee.fullname" . }}-pvc
          {{- if .Values.tolgee.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.tolgee.persistence.existingClaim }}{{ .Values.tolgee.persistence.existingClaim }}{{- else }}{{ include "tolgee.fullname" . }}-pvc{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
